# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'
use_frameworks!

target 'TestSnapKitAndRxSwift' do
    pod 'SnapKit'
    pod 'RxSwift', '6.2.0'
    pod 'RxCocoa', '6.2.0'
end
